# Generated by Django 3.0.4 on 2020-03-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lang',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='language',
            new_name='languages',
        ),
    ]
