# Generated by Django 3.0.4 on 2020-03-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0004_auto_20200315_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='languages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='snippet.Language'),
        ),
    ]
