# Generated by Django 3.0.4 on 2020-03-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0006_auto_20200316_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='pablic',
            field=models.BooleanField(default=False),
        ),
    ]
