# Generated by Django 3.0.4 on 2020-03-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0007_snippet_pablic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='pablic',
            new_name='public',
        ),
    ]
