# Generated by Django 3.0.4 on 2020-03-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0008_auto_20200319_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='language',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
